### ISSUE TITLE
这个能不能用python2的环境用啊

### ISSUE THREAD

**Issue by huangpeng0817** [Gourds/jms-assets-import#2]

**Comment by Gourds** [comment]
理论上应该可以，不过我看，我用他们的SDK就是python3环境的，所以建议还是用Python3，Python2的话，你可以确认下https://github.com/jumpserver/jumpserver-python-sdk 是不是有支持的SDK版本，或者可以只调用RestAPI来实现

**Comment by huangpeng0817** [comment]
> 理论上应该可以，不过我看，我用他们的SDK就是python3环境的，所以建议还是用Python3，Python2的话，你可以确认下https://github.com/jumpserver/jumpserver-python-sdk 是不是有支持的SDK版本，或者可以只调用RestAPI来实现

我试过不行的。我现在python2只能用restapi 重写。调用sdk会报错。

**Comment by Gourds** [comment]
嗯，用Restapi也蛮好的
